name: Run Tests
on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]

defaults:
  run:
    working-directory: HTTPShortcuts

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Android Tests
        run: ./gradlew app:testDebugUnitTest
        continue-on-error: true

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
